import React from "react";
import type { Metadata } from "next";
import { Golos_Text } from 'next/font/google'
import { Header } from "@/widgets/header";
import "./globals.css";
import { SubHeader } from "@/widgets/sub-header";

const golosText = Golos_Text({
    subsets: ['latin'],
    weight: ['400', '700']
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${golosText.className}`}
            >
                <SubHeader/>
                <Header/>
                {children}
            </body>
        </html>
    );
}
