import React from "react";
import type { Metadata } from "next";
import { Golos_Text } from 'next/font/google'
import StoreProvider from "@/redux-store/store-provider";

import "./globals.css";

const golosText = Golos_Text({
    subsets: ['latin'],
    weight: ['400', '500', '600', '700']
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${golosText.className} `}  >
                <StoreProvider>
                    <div className="min-h-screen flex flex-col">{children}</div>
                </StoreProvider>
            </body>
        </html>
    );
}
