import React from "react";
import type { Metadata } from "next";
import { Golos_Text } from 'next/font/google'
import { Providers } from "@/shared/ui/providers";
import "./globals.css";

const golosText = Golos_Text({
    subsets: ['latin'],
    weight: ['400', '500', '600', '700']
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${golosText.className} flex flex-col h-screen `}  >
                <Providers>{children}</Providers>
            </body>
        </html >
    );
}
